set(root "${TEST_DIR}/uninstall fixture")
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}/stage/prefix/bin" "${root}/build")
file(WRITE "${root}/stage/prefix/bin/lwm" "installed")
file(WRITE "${root}/stage/prefix/bin/unrelated" "keep")
file(CREATE_LINK missing-target "${root}/stage/prefix/bin/lwmctl" SYMBOLIC)
file(WRITE "${root}/build/install_manifest.txt" "/prefix/bin/lwm\n/prefix/bin/lwmctl\n/prefix/bin/lwm-notify\n")
set(ENV{DESTDIR} "${root}/stage")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DMANIFEST=${root}/build/install_manifest.txt"
                -P "${UNINSTALL_SCRIPT}" RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR EXISTS "${root}/stage/prefix/bin/lwm" OR IS_SYMLINK "${root}/stage/prefix/bin/lwmctl")
    message(FATAL_ERROR "Uninstall failed to remove the recorded files")
endif()
if(NOT EXISTS "${root}/stage/prefix/bin/unrelated")
    message(FATAL_ERROR "Uninstall removed an unrecorded file")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DMANIFEST=${root}/absent"
                -P "${UNINSTALL_SCRIPT}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0)
    message(FATAL_ERROR "Missing manifest must fail")
endif()
file(WRITE "${root}/build/install_manifest.txt" "/prefix/bin\n")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DMANIFEST=${root}/build/install_manifest.txt"
                -P "${UNINSTALL_SCRIPT}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(result EQUAL 0 OR NOT EXISTS "${root}/stage/prefix/bin/unrelated")
    message(FATAL_ERROR "Uninstall must reject directory entries")
endif()
file(REMOVE_RECURSE "${root}")
