if(NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "Install manifest not found: ${MANIFEST}. Use the build directory that installed LWM.")
endif()

file(STRINGS "${MANIFEST}" installed_files)
foreach(path IN LISTS installed_files)
    set(path "$ENV{DESTDIR}${path}")
    if(IS_DIRECTORY "${path}" AND NOT IS_SYMLINK "${path}")
        message(FATAL_ERROR "Refusing to remove a directory from the install manifest: ${path}")
    endif()
    if(EXISTS "${path}" OR IS_SYMLINK "${path}")
        message(STATUS "Removing ${path}")
        file(REMOVE "${path}")
        if(EXISTS "${path}" OR IS_SYMLINK "${path}")
            message(FATAL_ERROR "Could not remove ${path}")
        endif()
    endif()
endforeach()
